### ISSUE TITLE
Skip Button wird komisch ausgegraut

### ISSUE THREAD

**Issue by aul12** [SoPra-Team-10/Client#31]
Keine Ahnung wie das gedacht war, aber das highlight/ausgrauen des Skip Buttons passt irgendwie nicht damit zusammen ob man skippen kann oder nicht

**Comment by Mvsvh** [comment]
Ist noch auch Relikt aus den CSS-Styles. Hatte den active selector definiert, brauchen wir aber nicht. Mache ich weg.
