### ISSUE TITLE
Klatscher verschwinden manchmal

### ISSUE THREAD

**Issue by Timmifixedit** [SoPra-Team-10/Client#33]

**Comment by Timmifixedit** [comment]
Passiert auch manchmal beim Quaffle. Passiert wahrscheinlich, wenn der Ball zum Rand des Spielfelds geworfen wird

**Comment by Mvsvh** [comment]
Verschwinden die Elemente auch aus dem DOM?

**Comment by Mvsvh** [comment]
Sollte jetzt gefixed sein.
