### ISSUE TITLE
Timestamp bei Nachrichten Millisekunden müssen dreistellig sein

### ISSUE THREAD

**Issue by aul12** [SoPra-Team-10/Client#52]

**Comment by TarikEnderes** [comment]
Bei mir sind die dreistellig

**Comment by aul12** [comment]
Leading Zeros fehlen aber wenn kleiner als 100

**Comment by aul12** [comment]
Ist jetzt gefixt, bei millisekunden kleiner 10 wurde vorne nur eine Null angefügt
