### ISSUE TITLE
Während des Wartens auf den zweiten Spieler darf nicht pausiert werden können

### ISSUE THREAD

**Issue by aul12** [SoPra-Team-10/Client#55]

**Comment by TarikEnderes** [comment]
Der Standard sagt: Eine Pause-Request kann von allen spielenden Clients an den Server gesendet werden.
Also von mir aus gesehen unabhängig davon ob ich dran bin oder nicht.

**Comment by TarikEnderes** [comment]
Es macht auch keinen Sinn, dass ich auf den anderen Spieler warten muss bis ich pausieren kann.

**Comment by TarikEnderes** [comment]
Ach jetzt versteh ich das.

**Comment by aul12** [comment]
Auch nicht während die TeamFormation aufgestellt wird
